// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/agui-coder/simple-admin-pay-rpc/ent/demoorder"
	"github.com/agui-coder/simple-admin-pay-rpc/ent/order"
	"github.com/agui-coder/simple-admin-pay-rpc/ent/orderextension"
	"github.com/agui-coder/simple-admin-pay-rpc/ent/refund"
	"github.com/agui-coder/simple-admin-pay-rpc/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	demoorderMixin := schema.DemoOrder{}.Mixin()
	demoorderMixinHooks1 := demoorderMixin[1].Hooks()
	demoorder.Hooks[0] = demoorderMixinHooks1[0]
	demoorderMixinInters1 := demoorderMixin[1].Interceptors()
	demoorder.Interceptors[0] = demoorderMixinInters1[0]
	demoorderMixinFields0 := demoorderMixin[0].Fields()
	_ = demoorderMixinFields0
	demoorderFields := schema.DemoOrder{}.Fields()
	_ = demoorderFields
	// demoorderDescCreatedAt is the schema descriptor for created_at field.
	demoorderDescCreatedAt := demoorderMixinFields0[1].Descriptor()
	// demoorder.DefaultCreatedAt holds the default value on creation for the created_at field.
	demoorder.DefaultCreatedAt = demoorderDescCreatedAt.Default.(func() time.Time)
	// demoorderDescUpdatedAt is the schema descriptor for updated_at field.
	demoorderDescUpdatedAt := demoorderMixinFields0[2].Descriptor()
	// demoorder.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	demoorder.DefaultUpdatedAt = demoorderDescUpdatedAt.Default.(func() time.Time)
	// demoorder.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	demoorder.UpdateDefaultUpdatedAt = demoorderDescUpdatedAt.UpdateDefault.(func() time.Time)
	orderMixin := schema.Order{}.Mixin()
	orderMixinHooks2 := orderMixin[2].Hooks()
	order.Hooks[0] = orderMixinHooks2[0]
	orderMixinInters2 := orderMixin[2].Interceptors()
	order.Interceptors[0] = orderMixinInters2[0]
	orderMixinFields0 := orderMixin[0].Fields()
	_ = orderMixinFields0
	orderMixinFields1 := orderMixin[1].Fields()
	_ = orderMixinFields1
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescCreatedAt is the schema descriptor for created_at field.
	orderDescCreatedAt := orderMixinFields0[1].Descriptor()
	// order.DefaultCreatedAt holds the default value on creation for the created_at field.
	order.DefaultCreatedAt = orderDescCreatedAt.Default.(func() time.Time)
	// orderDescUpdatedAt is the schema descriptor for updated_at field.
	orderDescUpdatedAt := orderMixinFields0[2].Descriptor()
	// order.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	order.DefaultUpdatedAt = orderDescUpdatedAt.Default.(func() time.Time)
	// order.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	order.UpdateDefaultUpdatedAt = orderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// orderDescStatus is the schema descriptor for status field.
	orderDescStatus := orderMixinFields1[0].Descriptor()
	// order.DefaultStatus holds the default value on creation for the status field.
	order.DefaultStatus = orderDescStatus.Default.(uint8)
	orderextensionMixin := schema.OrderExtension{}.Mixin()
	orderextensionMixinHooks2 := orderextensionMixin[2].Hooks()
	orderextension.Hooks[0] = orderextensionMixinHooks2[0]
	orderextensionMixinInters2 := orderextensionMixin[2].Interceptors()
	orderextension.Interceptors[0] = orderextensionMixinInters2[0]
	orderextensionMixinFields0 := orderextensionMixin[0].Fields()
	_ = orderextensionMixinFields0
	orderextensionMixinFields1 := orderextensionMixin[1].Fields()
	_ = orderextensionMixinFields1
	orderextensionFields := schema.OrderExtension{}.Fields()
	_ = orderextensionFields
	// orderextensionDescCreatedAt is the schema descriptor for created_at field.
	orderextensionDescCreatedAt := orderextensionMixinFields0[1].Descriptor()
	// orderextension.DefaultCreatedAt holds the default value on creation for the created_at field.
	orderextension.DefaultCreatedAt = orderextensionDescCreatedAt.Default.(func() time.Time)
	// orderextensionDescUpdatedAt is the schema descriptor for updated_at field.
	orderextensionDescUpdatedAt := orderextensionMixinFields0[2].Descriptor()
	// orderextension.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	orderextension.DefaultUpdatedAt = orderextensionDescUpdatedAt.Default.(func() time.Time)
	// orderextension.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	orderextension.UpdateDefaultUpdatedAt = orderextensionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// orderextensionDescStatus is the schema descriptor for status field.
	orderextensionDescStatus := orderextensionMixinFields1[0].Descriptor()
	// orderextension.DefaultStatus holds the default value on creation for the status field.
	orderextension.DefaultStatus = orderextensionDescStatus.Default.(uint8)
	refundMixin := schema.Refund{}.Mixin()
	refundMixinHooks2 := refundMixin[2].Hooks()
	refund.Hooks[0] = refundMixinHooks2[0]
	refundMixinInters2 := refundMixin[2].Interceptors()
	refund.Interceptors[0] = refundMixinInters2[0]
	refundMixinFields0 := refundMixin[0].Fields()
	_ = refundMixinFields0
	refundMixinFields1 := refundMixin[1].Fields()
	_ = refundMixinFields1
	refundFields := schema.Refund{}.Fields()
	_ = refundFields
	// refundDescCreatedAt is the schema descriptor for created_at field.
	refundDescCreatedAt := refundMixinFields0[1].Descriptor()
	// refund.DefaultCreatedAt holds the default value on creation for the created_at field.
	refund.DefaultCreatedAt = refundDescCreatedAt.Default.(func() time.Time)
	// refundDescUpdatedAt is the schema descriptor for updated_at field.
	refundDescUpdatedAt := refundMixinFields0[2].Descriptor()
	// refund.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	refund.DefaultUpdatedAt = refundDescUpdatedAt.Default.(func() time.Time)
	// refund.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	refund.UpdateDefaultUpdatedAt = refundDescUpdatedAt.UpdateDefault.(func() time.Time)
	// refundDescStatus is the schema descriptor for status field.
	refundDescStatus := refundMixinFields1[0].Descriptor()
	// refund.DefaultStatus holds the default value on creation for the status field.
	refund.DefaultStatus = refundDescStatus.Default.(uint8)
}

const (
	Version = "v0.12.5"                                         // Version of ent codegen.
	Sum     = "h1:KREM5E4CSoej4zeGa88Ou/gfturAnpUv0mzAjch1sj4=" // Sum of ent codegen.
)
