// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"github.com/agui-coder/simple-admin-pay-rpc/ent/demoorder"
	"github.com/agui-coder/simple-admin-pay-rpc/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DemoOrderQuery is the builder for querying DemoOrder entities.
type DemoOrderQuery struct {
	config
	ctx        *QueryContext
	order      []demoorder.OrderOption
	inters     []Interceptor
	predicates []predicate.DemoOrder
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DemoOrderQuery builder.
func (doq *DemoOrderQuery) Where(ps ...predicate.DemoOrder) *DemoOrderQuery {
	doq.predicates = append(doq.predicates, ps...)
	return doq
}

// Limit the number of records to be returned by this query.
func (doq *DemoOrderQuery) Limit(limit int) *DemoOrderQuery {
	doq.ctx.Limit = &limit
	return doq
}

// Offset to start from.
func (doq *DemoOrderQuery) Offset(offset int) *DemoOrderQuery {
	doq.ctx.Offset = &offset
	return doq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (doq *DemoOrderQuery) Unique(unique bool) *DemoOrderQuery {
	doq.ctx.Unique = &unique
	return doq
}

// Order specifies how the records should be ordered.
func (doq *DemoOrderQuery) Order(o ...demoorder.OrderOption) *DemoOrderQuery {
	doq.order = append(doq.order, o...)
	return doq
}

// First returns the first DemoOrder entity from the query.
// Returns a *NotFoundError when no DemoOrder was found.
func (doq *DemoOrderQuery) First(ctx context.Context) (*DemoOrder, error) {
	nodes, err := doq.Limit(1).All(setContextOp(ctx, doq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{demoorder.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (doq *DemoOrderQuery) FirstX(ctx context.Context) *DemoOrder {
	node, err := doq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DemoOrder ID from the query.
// Returns a *NotFoundError when no DemoOrder ID was found.
func (doq *DemoOrderQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = doq.Limit(1).IDs(setContextOp(ctx, doq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{demoorder.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (doq *DemoOrderQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := doq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DemoOrder entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DemoOrder entity is found.
// Returns a *NotFoundError when no DemoOrder entities are found.
func (doq *DemoOrderQuery) Only(ctx context.Context) (*DemoOrder, error) {
	nodes, err := doq.Limit(2).All(setContextOp(ctx, doq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{demoorder.Label}
	default:
		return nil, &NotSingularError{demoorder.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (doq *DemoOrderQuery) OnlyX(ctx context.Context) *DemoOrder {
	node, err := doq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DemoOrder ID in the query.
// Returns a *NotSingularError when more than one DemoOrder ID is found.
// Returns a *NotFoundError when no entities are found.
func (doq *DemoOrderQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = doq.Limit(2).IDs(setContextOp(ctx, doq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{demoorder.Label}
	default:
		err = &NotSingularError{demoorder.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (doq *DemoOrderQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := doq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DemoOrders.
func (doq *DemoOrderQuery) All(ctx context.Context) ([]*DemoOrder, error) {
	ctx = setContextOp(ctx, doq.ctx, "All")
	if err := doq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DemoOrder, *DemoOrderQuery]()
	return withInterceptors[[]*DemoOrder](ctx, doq, qr, doq.inters)
}

// AllX is like All, but panics if an error occurs.
func (doq *DemoOrderQuery) AllX(ctx context.Context) []*DemoOrder {
	nodes, err := doq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DemoOrder IDs.
func (doq *DemoOrderQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if doq.ctx.Unique == nil && doq.path != nil {
		doq.Unique(true)
	}
	ctx = setContextOp(ctx, doq.ctx, "IDs")
	if err = doq.Select(demoorder.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (doq *DemoOrderQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := doq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (doq *DemoOrderQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, doq.ctx, "Count")
	if err := doq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, doq, querierCount[*DemoOrderQuery](), doq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (doq *DemoOrderQuery) CountX(ctx context.Context) int {
	count, err := doq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (doq *DemoOrderQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, doq.ctx, "Exist")
	switch _, err := doq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (doq *DemoOrderQuery) ExistX(ctx context.Context) bool {
	exist, err := doq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DemoOrderQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (doq *DemoOrderQuery) Clone() *DemoOrderQuery {
	if doq == nil {
		return nil
	}
	return &DemoOrderQuery{
		config:     doq.config,
		ctx:        doq.ctx.Clone(),
		order:      append([]demoorder.OrderOption{}, doq.order...),
		inters:     append([]Interceptor{}, doq.inters...),
		predicates: append([]predicate.DemoOrder{}, doq.predicates...),
		// clone intermediate query.
		sql:  doq.sql.Clone(),
		path: doq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DemoOrder.Query().
//		GroupBy(demoorder.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (doq *DemoOrderQuery) GroupBy(field string, fields ...string) *DemoOrderGroupBy {
	doq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DemoOrderGroupBy{build: doq}
	grbuild.flds = &doq.ctx.Fields
	grbuild.label = demoorder.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.DemoOrder.Query().
//		Select(demoorder.FieldCreatedAt).
//		Scan(ctx, &v)
func (doq *DemoOrderQuery) Select(fields ...string) *DemoOrderSelect {
	doq.ctx.Fields = append(doq.ctx.Fields, fields...)
	sbuild := &DemoOrderSelect{DemoOrderQuery: doq}
	sbuild.label = demoorder.Label
	sbuild.flds, sbuild.scan = &doq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DemoOrderSelect configured with the given aggregations.
func (doq *DemoOrderQuery) Aggregate(fns ...AggregateFunc) *DemoOrderSelect {
	return doq.Select().Aggregate(fns...)
}

func (doq *DemoOrderQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range doq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, doq); err != nil {
				return err
			}
		}
	}
	for _, f := range doq.ctx.Fields {
		if !demoorder.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if doq.path != nil {
		prev, err := doq.path(ctx)
		if err != nil {
			return err
		}
		doq.sql = prev
	}
	return nil
}

func (doq *DemoOrderQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DemoOrder, error) {
	var (
		nodes = []*DemoOrder{}
		_spec = doq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DemoOrder).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DemoOrder{config: doq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, doq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (doq *DemoOrderQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := doq.querySpec()
	_spec.Node.Columns = doq.ctx.Fields
	if len(doq.ctx.Fields) > 0 {
		_spec.Unique = doq.ctx.Unique != nil && *doq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, doq.driver, _spec)
}

func (doq *DemoOrderQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(demoorder.Table, demoorder.Columns, sqlgraph.NewFieldSpec(demoorder.FieldID, field.TypeUint64))
	_spec.From = doq.sql
	if unique := doq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if doq.path != nil {
		_spec.Unique = true
	}
	if fields := doq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, demoorder.FieldID)
		for i := range fields {
			if fields[i] != demoorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := doq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := doq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := doq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := doq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (doq *DemoOrderQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(doq.driver.Dialect())
	t1 := builder.Table(demoorder.Table)
	columns := doq.ctx.Fields
	if len(columns) == 0 {
		columns = demoorder.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if doq.sql != nil {
		selector = doq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if doq.ctx.Unique != nil && *doq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range doq.predicates {
		p(selector)
	}
	for _, p := range doq.order {
		p(selector)
	}
	if offset := doq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := doq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DemoOrderGroupBy is the group-by builder for DemoOrder entities.
type DemoOrderGroupBy struct {
	selector
	build *DemoOrderQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dogb *DemoOrderGroupBy) Aggregate(fns ...AggregateFunc) *DemoOrderGroupBy {
	dogb.fns = append(dogb.fns, fns...)
	return dogb
}

// Scan applies the selector query and scans the result into the given value.
func (dogb *DemoOrderGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dogb.build.ctx, "GroupBy")
	if err := dogb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DemoOrderQuery, *DemoOrderGroupBy](ctx, dogb.build, dogb, dogb.build.inters, v)
}

func (dogb *DemoOrderGroupBy) sqlScan(ctx context.Context, root *DemoOrderQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(dogb.fns))
	for _, fn := range dogb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*dogb.flds)+len(dogb.fns))
		for _, f := range *dogb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*dogb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dogb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DemoOrderSelect is the builder for selecting fields of DemoOrder entities.
type DemoOrderSelect struct {
	*DemoOrderQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (dos *DemoOrderSelect) Aggregate(fns ...AggregateFunc) *DemoOrderSelect {
	dos.fns = append(dos.fns, fns...)
	return dos
}

// Scan applies the selector query and scans the result into the given value.
func (dos *DemoOrderSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dos.ctx, "Select")
	if err := dos.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DemoOrderQuery, *DemoOrderSelect](ctx, dos.DemoOrderQuery, dos, dos.inters, v)
}

func (dos *DemoOrderSelect) sqlScan(ctx context.Context, root *DemoOrderQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(dos.fns))
	for _, fn := range dos.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*dos.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dos.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
