// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agui-coder/simple-admin-pay-rpc/ent/notifylog"
	"github.com/agui-coder/simple-admin-pay-rpc/ent/predicate"
)

// NotifyLogQuery is the builder for querying NotifyLog entities.
type NotifyLogQuery struct {
	config
	ctx        *QueryContext
	order      []notifylog.OrderOption
	inters     []Interceptor
	predicates []predicate.NotifyLog
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NotifyLogQuery builder.
func (nlq *NotifyLogQuery) Where(ps ...predicate.NotifyLog) *NotifyLogQuery {
	nlq.predicates = append(nlq.predicates, ps...)
	return nlq
}

// Limit the number of records to be returned by this query.
func (nlq *NotifyLogQuery) Limit(limit int) *NotifyLogQuery {
	nlq.ctx.Limit = &limit
	return nlq
}

// Offset to start from.
func (nlq *NotifyLogQuery) Offset(offset int) *NotifyLogQuery {
	nlq.ctx.Offset = &offset
	return nlq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (nlq *NotifyLogQuery) Unique(unique bool) *NotifyLogQuery {
	nlq.ctx.Unique = &unique
	return nlq
}

// Order specifies how the records should be ordered.
func (nlq *NotifyLogQuery) Order(o ...notifylog.OrderOption) *NotifyLogQuery {
	nlq.order = append(nlq.order, o...)
	return nlq
}

// First returns the first NotifyLog entity from the query.
// Returns a *NotFoundError when no NotifyLog was found.
func (nlq *NotifyLogQuery) First(ctx context.Context) (*NotifyLog, error) {
	nodes, err := nlq.Limit(1).All(setContextOp(ctx, nlq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{notifylog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (nlq *NotifyLogQuery) FirstX(ctx context.Context) *NotifyLog {
	node, err := nlq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first NotifyLog ID from the query.
// Returns a *NotFoundError when no NotifyLog ID was found.
func (nlq *NotifyLogQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = nlq.Limit(1).IDs(setContextOp(ctx, nlq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{notifylog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (nlq *NotifyLogQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := nlq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single NotifyLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one NotifyLog entity is found.
// Returns a *NotFoundError when no NotifyLog entities are found.
func (nlq *NotifyLogQuery) Only(ctx context.Context) (*NotifyLog, error) {
	nodes, err := nlq.Limit(2).All(setContextOp(ctx, nlq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{notifylog.Label}
	default:
		return nil, &NotSingularError{notifylog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (nlq *NotifyLogQuery) OnlyX(ctx context.Context) *NotifyLog {
	node, err := nlq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only NotifyLog ID in the query.
// Returns a *NotSingularError when more than one NotifyLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (nlq *NotifyLogQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = nlq.Limit(2).IDs(setContextOp(ctx, nlq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{notifylog.Label}
	default:
		err = &NotSingularError{notifylog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (nlq *NotifyLogQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := nlq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of NotifyLogs.
func (nlq *NotifyLogQuery) All(ctx context.Context) ([]*NotifyLog, error) {
	ctx = setContextOp(ctx, nlq.ctx, "All")
	if err := nlq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*NotifyLog, *NotifyLogQuery]()
	return withInterceptors[[]*NotifyLog](ctx, nlq, qr, nlq.inters)
}

// AllX is like All, but panics if an error occurs.
func (nlq *NotifyLogQuery) AllX(ctx context.Context) []*NotifyLog {
	nodes, err := nlq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of NotifyLog IDs.
func (nlq *NotifyLogQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if nlq.ctx.Unique == nil && nlq.path != nil {
		nlq.Unique(true)
	}
	ctx = setContextOp(ctx, nlq.ctx, "IDs")
	if err = nlq.Select(notifylog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (nlq *NotifyLogQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := nlq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (nlq *NotifyLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, nlq.ctx, "Count")
	if err := nlq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, nlq, querierCount[*NotifyLogQuery](), nlq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (nlq *NotifyLogQuery) CountX(ctx context.Context) int {
	count, err := nlq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (nlq *NotifyLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, nlq.ctx, "Exist")
	switch _, err := nlq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (nlq *NotifyLogQuery) ExistX(ctx context.Context) bool {
	exist, err := nlq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NotifyLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (nlq *NotifyLogQuery) Clone() *NotifyLogQuery {
	if nlq == nil {
		return nil
	}
	return &NotifyLogQuery{
		config:     nlq.config,
		ctx:        nlq.ctx.Clone(),
		order:      append([]notifylog.OrderOption{}, nlq.order...),
		inters:     append([]Interceptor{}, nlq.inters...),
		predicates: append([]predicate.NotifyLog{}, nlq.predicates...),
		// clone intermediate query.
		sql:  nlq.sql.Clone(),
		path: nlq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.NotifyLog.Query().
//		GroupBy(notifylog.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (nlq *NotifyLogQuery) GroupBy(field string, fields ...string) *NotifyLogGroupBy {
	nlq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &NotifyLogGroupBy{build: nlq}
	grbuild.flds = &nlq.ctx.Fields
	grbuild.label = notifylog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.NotifyLog.Query().
//		Select(notifylog.FieldCreatedAt).
//		Scan(ctx, &v)
func (nlq *NotifyLogQuery) Select(fields ...string) *NotifyLogSelect {
	nlq.ctx.Fields = append(nlq.ctx.Fields, fields...)
	sbuild := &NotifyLogSelect{NotifyLogQuery: nlq}
	sbuild.label = notifylog.Label
	sbuild.flds, sbuild.scan = &nlq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a NotifyLogSelect configured with the given aggregations.
func (nlq *NotifyLogQuery) Aggregate(fns ...AggregateFunc) *NotifyLogSelect {
	return nlq.Select().Aggregate(fns...)
}

func (nlq *NotifyLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range nlq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, nlq); err != nil {
				return err
			}
		}
	}
	for _, f := range nlq.ctx.Fields {
		if !notifylog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if nlq.path != nil {
		prev, err := nlq.path(ctx)
		if err != nil {
			return err
		}
		nlq.sql = prev
	}
	return nil
}

func (nlq *NotifyLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*NotifyLog, error) {
	var (
		nodes = []*NotifyLog{}
		_spec = nlq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*NotifyLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &NotifyLog{config: nlq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, nlq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (nlq *NotifyLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := nlq.querySpec()
	_spec.Node.Columns = nlq.ctx.Fields
	if len(nlq.ctx.Fields) > 0 {
		_spec.Unique = nlq.ctx.Unique != nil && *nlq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, nlq.driver, _spec)
}

func (nlq *NotifyLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(notifylog.Table, notifylog.Columns, sqlgraph.NewFieldSpec(notifylog.FieldID, field.TypeUint64))
	_spec.From = nlq.sql
	if unique := nlq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if nlq.path != nil {
		_spec.Unique = true
	}
	if fields := nlq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notifylog.FieldID)
		for i := range fields {
			if fields[i] != notifylog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := nlq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := nlq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := nlq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := nlq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (nlq *NotifyLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(nlq.driver.Dialect())
	t1 := builder.Table(notifylog.Table)
	columns := nlq.ctx.Fields
	if len(columns) == 0 {
		columns = notifylog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if nlq.sql != nil {
		selector = nlq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if nlq.ctx.Unique != nil && *nlq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range nlq.predicates {
		p(selector)
	}
	for _, p := range nlq.order {
		p(selector)
	}
	if offset := nlq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := nlq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// NotifyLogGroupBy is the group-by builder for NotifyLog entities.
type NotifyLogGroupBy struct {
	selector
	build *NotifyLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (nlgb *NotifyLogGroupBy) Aggregate(fns ...AggregateFunc) *NotifyLogGroupBy {
	nlgb.fns = append(nlgb.fns, fns...)
	return nlgb
}

// Scan applies the selector query and scans the result into the given value.
func (nlgb *NotifyLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, nlgb.build.ctx, "GroupBy")
	if err := nlgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NotifyLogQuery, *NotifyLogGroupBy](ctx, nlgb.build, nlgb, nlgb.build.inters, v)
}

func (nlgb *NotifyLogGroupBy) sqlScan(ctx context.Context, root *NotifyLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(nlgb.fns))
	for _, fn := range nlgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*nlgb.flds)+len(nlgb.fns))
		for _, f := range *nlgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*nlgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := nlgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// NotifyLogSelect is the builder for selecting fields of NotifyLog entities.
type NotifyLogSelect struct {
	*NotifyLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (nls *NotifyLogSelect) Aggregate(fns ...AggregateFunc) *NotifyLogSelect {
	nls.fns = append(nls.fns, fns...)
	return nls
}

// Scan applies the selector query and scans the result into the given value.
func (nls *NotifyLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, nls.ctx, "Select")
	if err := nls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NotifyLogQuery, *NotifyLogSelect](ctx, nls.NotifyLogQuery, nls, nls.inters, v)
}

func (nls *NotifyLogSelect) sqlScan(ctx context.Context, root *NotifyLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(nls.fns))
	for _, fn := range nls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*nls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := nls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
