// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agui-coder/simple-admin-pay-rpc/ent/orderextension"
	"github.com/agui-coder/simple-admin-pay-rpc/ent/predicate"
)

// OrderExtensionDelete is the builder for deleting a OrderExtension entity.
type OrderExtensionDelete struct {
	config
	hooks    []Hook
	mutation *OrderExtensionMutation
}

// Where appends a list predicates to the OrderExtensionDelete builder.
func (oed *OrderExtensionDelete) Where(ps ...predicate.OrderExtension) *OrderExtensionDelete {
	oed.mutation.Where(ps...)
	return oed
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (oed *OrderExtensionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, oed.sqlExec, oed.mutation, oed.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (oed *OrderExtensionDelete) ExecX(ctx context.Context) int {
	n, err := oed.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (oed *OrderExtensionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(orderextension.Table, sqlgraph.NewFieldSpec(orderextension.FieldID, field.TypeUint64))
	if ps := oed.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, oed.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	oed.mutation.done = true
	return affected, err
}

// OrderExtensionDeleteOne is the builder for deleting a single OrderExtension entity.
type OrderExtensionDeleteOne struct {
	oed *OrderExtensionDelete
}

// Where appends a list predicates to the OrderExtensionDelete builder.
func (oedo *OrderExtensionDeleteOne) Where(ps ...predicate.OrderExtension) *OrderExtensionDeleteOne {
	oedo.oed.mutation.Where(ps...)
	return oedo
}

// Exec executes the deletion query.
func (oedo *OrderExtensionDeleteOne) Exec(ctx context.Context) error {
	n, err := oedo.oed.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{orderextension.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (oedo *OrderExtensionDeleteOne) ExecX(ctx context.Context) {
	if err := oedo.Exec(ctx); err != nil {
		panic(err)
	}
}
