// Code generated by ent, DO NOT EDIT.

package ent

import "time"

// set field if value's pointer is not nil.
func (a *AppUpdate) SetNotNilUpdatedAt(value *time.Time) *AppUpdate {
	if value != nil {
		return a.SetUpdatedAt(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppUpdateOne) SetNotNilUpdatedAt(value *time.Time) *AppUpdateOne {
	if value != nil {
		return a.SetUpdatedAt(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppCreate) SetNotNilUpdatedAt(value *time.Time) *AppCreate {
	if value != nil {
		return a.SetUpdatedAt(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppUpdate) SetNotNilStatus(value *uint8) *AppUpdate {
	if value != nil {
		return a.SetStatus(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppUpdateOne) SetNotNilStatus(value *uint8) *AppUpdateOne {
	if value != nil {
		return a.SetStatus(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppCreate) SetNotNilStatus(value *uint8) *AppCreate {
	if value != nil {
		return a.SetStatus(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppUpdate) SetNotNilDeletedAt(value *time.Time) *AppUpdate {
	if value != nil {
		return a.SetDeletedAt(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppUpdateOne) SetNotNilDeletedAt(value *time.Time) *AppUpdateOne {
	if value != nil {
		return a.SetDeletedAt(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppCreate) SetNotNilDeletedAt(value *time.Time) *AppCreate {
	if value != nil {
		return a.SetDeletedAt(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppUpdate) SetNotNilName(value *string) *AppUpdate {
	if value != nil {
		return a.SetName(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppUpdateOne) SetNotNilName(value *string) *AppUpdateOne {
	if value != nil {
		return a.SetName(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppCreate) SetNotNilName(value *string) *AppCreate {
	if value != nil {
		return a.SetName(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppUpdate) SetNotNilRemark(value *string) *AppUpdate {
	if value != nil {
		return a.SetRemark(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppUpdateOne) SetNotNilRemark(value *string) *AppUpdateOne {
	if value != nil {
		return a.SetRemark(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppCreate) SetNotNilRemark(value *string) *AppCreate {
	if value != nil {
		return a.SetRemark(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppUpdate) SetNotNilOrderNotifyURL(value *string) *AppUpdate {
	if value != nil {
		return a.SetOrderNotifyURL(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppUpdateOne) SetNotNilOrderNotifyURL(value *string) *AppUpdateOne {
	if value != nil {
		return a.SetOrderNotifyURL(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppCreate) SetNotNilOrderNotifyURL(value *string) *AppCreate {
	if value != nil {
		return a.SetOrderNotifyURL(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppUpdate) SetNotNilRefundNotifyURL(value *string) *AppUpdate {
	if value != nil {
		return a.SetRefundNotifyURL(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppUpdateOne) SetNotNilRefundNotifyURL(value *string) *AppUpdateOne {
	if value != nil {
		return a.SetRefundNotifyURL(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppCreate) SetNotNilRefundNotifyURL(value *string) *AppCreate {
	if value != nil {
		return a.SetRefundNotifyURL(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (c *ChannelUpdate) SetNotNilUpdatedAt(value *time.Time) *ChannelUpdate {
	if value != nil {
		return c.SetUpdatedAt(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *ChannelUpdateOne) SetNotNilUpdatedAt(value *time.Time) *ChannelUpdateOne {
	if value != nil {
		return c.SetUpdatedAt(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *ChannelCreate) SetNotNilUpdatedAt(value *time.Time) *ChannelCreate {
	if value != nil {
		return c.SetUpdatedAt(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *ChannelUpdate) SetNotNilStatus(value *uint8) *ChannelUpdate {
	if value != nil {
		return c.SetStatus(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *ChannelUpdateOne) SetNotNilStatus(value *uint8) *ChannelUpdateOne {
	if value != nil {
		return c.SetStatus(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *ChannelCreate) SetNotNilStatus(value *uint8) *ChannelCreate {
	if value != nil {
		return c.SetStatus(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *ChannelUpdate) SetNotNilDeletedAt(value *time.Time) *ChannelUpdate {
	if value != nil {
		return c.SetDeletedAt(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *ChannelUpdateOne) SetNotNilDeletedAt(value *time.Time) *ChannelUpdateOne {
	if value != nil {
		return c.SetDeletedAt(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *ChannelCreate) SetNotNilDeletedAt(value *time.Time) *ChannelCreate {
	if value != nil {
		return c.SetDeletedAt(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *ChannelUpdate) SetNotNilCode(value *string) *ChannelUpdate {
	if value != nil {
		return c.SetCode(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *ChannelUpdateOne) SetNotNilCode(value *string) *ChannelUpdateOne {
	if value != nil {
		return c.SetCode(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *ChannelCreate) SetNotNilCode(value *string) *ChannelCreate {
	if value != nil {
		return c.SetCode(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *ChannelUpdate) SetNotNilRemark(value *string) *ChannelUpdate {
	if value != nil {
		return c.SetRemark(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *ChannelUpdateOne) SetNotNilRemark(value *string) *ChannelUpdateOne {
	if value != nil {
		return c.SetRemark(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *ChannelCreate) SetNotNilRemark(value *string) *ChannelCreate {
	if value != nil {
		return c.SetRemark(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *ChannelUpdate) SetNotNilFeeRate(value *float64) *ChannelUpdate {
	if value != nil {
		return c.SetFeeRate(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *ChannelUpdateOne) SetNotNilFeeRate(value *float64) *ChannelUpdateOne {
	if value != nil {
		return c.SetFeeRate(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *ChannelCreate) SetNotNilFeeRate(value *float64) *ChannelCreate {
	if value != nil {
		return c.SetFeeRate(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *ChannelUpdate) SetNotNilAppID(value *uint64) *ChannelUpdate {
	if value != nil {
		return c.SetAppID(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *ChannelUpdateOne) SetNotNilAppID(value *uint64) *ChannelUpdateOne {
	if value != nil {
		return c.SetAppID(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *ChannelCreate) SetNotNilAppID(value *uint64) *ChannelCreate {
	if value != nil {
		return c.SetAppID(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *ChannelUpdate) SetNotNilConfig(value *string) *ChannelUpdate {
	if value != nil {
		return c.SetConfig(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *ChannelUpdateOne) SetNotNilConfig(value *string) *ChannelUpdateOne {
	if value != nil {
		return c.SetConfig(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *ChannelCreate) SetNotNilConfig(value *string) *ChannelCreate {
	if value != nil {
		return c.SetConfig(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdate) SetNotNilUpdatedAt(value *time.Time) *DemoOrderUpdate {
	if value != nil {
		return do.SetUpdatedAt(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdateOne) SetNotNilUpdatedAt(value *time.Time) *DemoOrderUpdateOne {
	if value != nil {
		return do.SetUpdatedAt(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderCreate) SetNotNilUpdatedAt(value *time.Time) *DemoOrderCreate {
	if value != nil {
		return do.SetUpdatedAt(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdate) SetNotNilDeletedAt(value *time.Time) *DemoOrderUpdate {
	if value != nil {
		return do.SetDeletedAt(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdateOne) SetNotNilDeletedAt(value *time.Time) *DemoOrderUpdateOne {
	if value != nil {
		return do.SetDeletedAt(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderCreate) SetNotNilDeletedAt(value *time.Time) *DemoOrderCreate {
	if value != nil {
		return do.SetDeletedAt(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdate) SetNotNilUserID(value *string) *DemoOrderUpdate {
	if value != nil {
		return do.SetUserID(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdateOne) SetNotNilUserID(value *string) *DemoOrderUpdateOne {
	if value != nil {
		return do.SetUserID(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderCreate) SetNotNilUserID(value *string) *DemoOrderCreate {
	if value != nil {
		return do.SetUserID(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdate) SetNotNilSpuID(value *uint64) *DemoOrderUpdate {
	if value != nil {
		return do.SetSpuID(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdateOne) SetNotNilSpuID(value *uint64) *DemoOrderUpdateOne {
	if value != nil {
		return do.SetSpuID(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderCreate) SetNotNilSpuID(value *uint64) *DemoOrderCreate {
	if value != nil {
		return do.SetSpuID(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdate) SetNotNilSpuName(value *string) *DemoOrderUpdate {
	if value != nil {
		return do.SetSpuName(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdateOne) SetNotNilSpuName(value *string) *DemoOrderUpdateOne {
	if value != nil {
		return do.SetSpuName(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderCreate) SetNotNilSpuName(value *string) *DemoOrderCreate {
	if value != nil {
		return do.SetSpuName(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdate) SetNotNilPrice(value *int32) *DemoOrderUpdate {
	if value != nil {
		return do.SetPrice(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdateOne) SetNotNilPrice(value *int32) *DemoOrderUpdateOne {
	if value != nil {
		return do.SetPrice(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderCreate) SetNotNilPrice(value *int32) *DemoOrderCreate {
	if value != nil {
		return do.SetPrice(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdate) SetNotNilPayStatus(value *bool) *DemoOrderUpdate {
	if value != nil {
		return do.SetPayStatus(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdateOne) SetNotNilPayStatus(value *bool) *DemoOrderUpdateOne {
	if value != nil {
		return do.SetPayStatus(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderCreate) SetNotNilPayStatus(value *bool) *DemoOrderCreate {
	if value != nil {
		return do.SetPayStatus(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdate) SetNotNilPayOrderId(value *uint64) *DemoOrderUpdate {
	if value != nil {
		return do.SetPayOrderId(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdateOne) SetNotNilPayOrderId(value *uint64) *DemoOrderUpdateOne {
	if value != nil {
		return do.SetPayOrderId(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderCreate) SetNotNilPayOrderId(value *uint64) *DemoOrderCreate {
	if value != nil {
		return do.SetPayOrderId(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdate) SetNotNilPayTime(value *time.Time) *DemoOrderUpdate {
	if value != nil {
		return do.SetPayTime(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdateOne) SetNotNilPayTime(value *time.Time) *DemoOrderUpdateOne {
	if value != nil {
		return do.SetPayTime(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderCreate) SetNotNilPayTime(value *time.Time) *DemoOrderCreate {
	if value != nil {
		return do.SetPayTime(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdate) SetNotNilPayChannelCode(value *string) *DemoOrderUpdate {
	if value != nil {
		return do.SetPayChannelCode(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdateOne) SetNotNilPayChannelCode(value *string) *DemoOrderUpdateOne {
	if value != nil {
		return do.SetPayChannelCode(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderCreate) SetNotNilPayChannelCode(value *string) *DemoOrderCreate {
	if value != nil {
		return do.SetPayChannelCode(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdate) SetNotNilPayRefundID(value *uint64) *DemoOrderUpdate {
	if value != nil {
		return do.SetPayRefundID(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdateOne) SetNotNilPayRefundID(value *uint64) *DemoOrderUpdateOne {
	if value != nil {
		return do.SetPayRefundID(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderCreate) SetNotNilPayRefundID(value *uint64) *DemoOrderCreate {
	if value != nil {
		return do.SetPayRefundID(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdate) SetNotNilRefundPrice(value *int32) *DemoOrderUpdate {
	if value != nil {
		return do.SetRefundPrice(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdateOne) SetNotNilRefundPrice(value *int32) *DemoOrderUpdateOne {
	if value != nil {
		return do.SetRefundPrice(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderCreate) SetNotNilRefundPrice(value *int32) *DemoOrderCreate {
	if value != nil {
		return do.SetRefundPrice(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdate) SetNotNilRefundTime(value *time.Time) *DemoOrderUpdate {
	if value != nil {
		return do.SetRefundTime(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderUpdateOne) SetNotNilRefundTime(value *time.Time) *DemoOrderUpdateOne {
	if value != nil {
		return do.SetRefundTime(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (do *DemoOrderCreate) SetNotNilRefundTime(value *time.Time) *DemoOrderCreate {
	if value != nil {
		return do.SetRefundTime(*value)
	}
	return do
}

// set field if value's pointer is not nil.
func (nl *NotifyLogUpdate) SetNotNilUpdatedAt(value *time.Time) *NotifyLogUpdate {
	if value != nil {
		return nl.SetUpdatedAt(*value)
	}
	return nl
}

// set field if value's pointer is not nil.
func (nl *NotifyLogUpdateOne) SetNotNilUpdatedAt(value *time.Time) *NotifyLogUpdateOne {
	if value != nil {
		return nl.SetUpdatedAt(*value)
	}
	return nl
}

// set field if value's pointer is not nil.
func (nl *NotifyLogCreate) SetNotNilUpdatedAt(value *time.Time) *NotifyLogCreate {
	if value != nil {
		return nl.SetUpdatedAt(*value)
	}
	return nl
}

// set field if value's pointer is not nil.
func (nl *NotifyLogUpdate) SetNotNilStatus(value *uint8) *NotifyLogUpdate {
	if value != nil {
		return nl.SetStatus(*value)
	}
	return nl
}

// set field if value's pointer is not nil.
func (nl *NotifyLogUpdateOne) SetNotNilStatus(value *uint8) *NotifyLogUpdateOne {
	if value != nil {
		return nl.SetStatus(*value)
	}
	return nl
}

// set field if value's pointer is not nil.
func (nl *NotifyLogCreate) SetNotNilStatus(value *uint8) *NotifyLogCreate {
	if value != nil {
		return nl.SetStatus(*value)
	}
	return nl
}

// set field if value's pointer is not nil.
func (nl *NotifyLogUpdate) SetNotNilDeletedAt(value *time.Time) *NotifyLogUpdate {
	if value != nil {
		return nl.SetDeletedAt(*value)
	}
	return nl
}

// set field if value's pointer is not nil.
func (nl *NotifyLogUpdateOne) SetNotNilDeletedAt(value *time.Time) *NotifyLogUpdateOne {
	if value != nil {
		return nl.SetDeletedAt(*value)
	}
	return nl
}

// set field if value's pointer is not nil.
func (nl *NotifyLogCreate) SetNotNilDeletedAt(value *time.Time) *NotifyLogCreate {
	if value != nil {
		return nl.SetDeletedAt(*value)
	}
	return nl
}

// set field if value's pointer is not nil.
func (nl *NotifyLogUpdate) SetNotNilTaskID(value *uint64) *NotifyLogUpdate {
	if value != nil {
		return nl.SetTaskID(*value)
	}
	return nl
}

// set field if value's pointer is not nil.
func (nl *NotifyLogUpdateOne) SetNotNilTaskID(value *uint64) *NotifyLogUpdateOne {
	if value != nil {
		return nl.SetTaskID(*value)
	}
	return nl
}

// set field if value's pointer is not nil.
func (nl *NotifyLogCreate) SetNotNilTaskID(value *uint64) *NotifyLogCreate {
	if value != nil {
		return nl.SetTaskID(*value)
	}
	return nl
}

// set field if value's pointer is not nil.
func (nl *NotifyLogUpdate) SetNotNilNotifyTimes(value *int8) *NotifyLogUpdate {
	if value != nil {
		return nl.SetNotifyTimes(*value)
	}
	return nl
}

// set field if value's pointer is not nil.
func (nl *NotifyLogUpdateOne) SetNotNilNotifyTimes(value *int8) *NotifyLogUpdateOne {
	if value != nil {
		return nl.SetNotifyTimes(*value)
	}
	return nl
}

// set field if value's pointer is not nil.
func (nl *NotifyLogCreate) SetNotNilNotifyTimes(value *int8) *NotifyLogCreate {
	if value != nil {
		return nl.SetNotifyTimes(*value)
	}
	return nl
}

// set field if value's pointer is not nil.
func (nl *NotifyLogUpdate) SetNotNilResponse(value *string) *NotifyLogUpdate {
	if value != nil {
		return nl.SetResponse(*value)
	}
	return nl
}

// set field if value's pointer is not nil.
func (nl *NotifyLogUpdateOne) SetNotNilResponse(value *string) *NotifyLogUpdateOne {
	if value != nil {
		return nl.SetResponse(*value)
	}
	return nl
}

// set field if value's pointer is not nil.
func (nl *NotifyLogCreate) SetNotNilResponse(value *string) *NotifyLogCreate {
	if value != nil {
		return nl.SetResponse(*value)
	}
	return nl
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskUpdate) SetNotNilUpdatedAt(value *time.Time) *NotifyTaskUpdate {
	if value != nil {
		return nt.SetUpdatedAt(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskUpdateOne) SetNotNilUpdatedAt(value *time.Time) *NotifyTaskUpdateOne {
	if value != nil {
		return nt.SetUpdatedAt(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskCreate) SetNotNilUpdatedAt(value *time.Time) *NotifyTaskCreate {
	if value != nil {
		return nt.SetUpdatedAt(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskUpdate) SetNotNilStatus(value *uint8) *NotifyTaskUpdate {
	if value != nil {
		return nt.SetStatus(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskUpdateOne) SetNotNilStatus(value *uint8) *NotifyTaskUpdateOne {
	if value != nil {
		return nt.SetStatus(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskCreate) SetNotNilStatus(value *uint8) *NotifyTaskCreate {
	if value != nil {
		return nt.SetStatus(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskUpdate) SetNotNilDeletedAt(value *time.Time) *NotifyTaskUpdate {
	if value != nil {
		return nt.SetDeletedAt(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskUpdateOne) SetNotNilDeletedAt(value *time.Time) *NotifyTaskUpdateOne {
	if value != nil {
		return nt.SetDeletedAt(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskCreate) SetNotNilDeletedAt(value *time.Time) *NotifyTaskCreate {
	if value != nil {
		return nt.SetDeletedAt(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskUpdate) SetNotNilAppID(value *uint64) *NotifyTaskUpdate {
	if value != nil {
		return nt.SetAppID(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskUpdateOne) SetNotNilAppID(value *uint64) *NotifyTaskUpdateOne {
	if value != nil {
		return nt.SetAppID(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskCreate) SetNotNilAppID(value *uint64) *NotifyTaskCreate {
	if value != nil {
		return nt.SetAppID(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskUpdate) SetNotNilType(value *int) *NotifyTaskUpdate {
	if value != nil {
		return nt.SetType(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskUpdateOne) SetNotNilType(value *int) *NotifyTaskUpdateOne {
	if value != nil {
		return nt.SetType(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskCreate) SetNotNilType(value *int) *NotifyTaskCreate {
	if value != nil {
		return nt.SetType(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskUpdate) SetNotNilDataID(value *uint64) *NotifyTaskUpdate {
	if value != nil {
		return nt.SetDataID(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskUpdateOne) SetNotNilDataID(value *uint64) *NotifyTaskUpdateOne {
	if value != nil {
		return nt.SetDataID(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskCreate) SetNotNilDataID(value *uint64) *NotifyTaskCreate {
	if value != nil {
		return nt.SetDataID(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskUpdate) SetNotNilMerchantOrderID(value *string) *NotifyTaskUpdate {
	if value != nil {
		return nt.SetMerchantOrderID(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskUpdateOne) SetNotNilMerchantOrderID(value *string) *NotifyTaskUpdateOne {
	if value != nil {
		return nt.SetMerchantOrderID(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskCreate) SetNotNilMerchantOrderID(value *string) *NotifyTaskCreate {
	if value != nil {
		return nt.SetMerchantOrderID(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskUpdate) SetNotNilNextNotifyTime(value *time.Time) *NotifyTaskUpdate {
	if value != nil {
		return nt.SetNextNotifyTime(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskUpdateOne) SetNotNilNextNotifyTime(value *time.Time) *NotifyTaskUpdateOne {
	if value != nil {
		return nt.SetNextNotifyTime(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskCreate) SetNotNilNextNotifyTime(value *time.Time) *NotifyTaskCreate {
	if value != nil {
		return nt.SetNextNotifyTime(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskUpdate) SetNotNilLastExecuteTime(value *time.Time) *NotifyTaskUpdate {
	if value != nil {
		return nt.SetLastExecuteTime(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskUpdateOne) SetNotNilLastExecuteTime(value *time.Time) *NotifyTaskUpdateOne {
	if value != nil {
		return nt.SetLastExecuteTime(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskCreate) SetNotNilLastExecuteTime(value *time.Time) *NotifyTaskCreate {
	if value != nil {
		return nt.SetLastExecuteTime(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskUpdate) SetNotNilNotifyTimes(value *int8) *NotifyTaskUpdate {
	if value != nil {
		return nt.SetNotifyTimes(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskUpdateOne) SetNotNilNotifyTimes(value *int8) *NotifyTaskUpdateOne {
	if value != nil {
		return nt.SetNotifyTimes(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskCreate) SetNotNilNotifyTimes(value *int8) *NotifyTaskCreate {
	if value != nil {
		return nt.SetNotifyTimes(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskUpdate) SetNotNilMaxNotifyTimes(value *int8) *NotifyTaskUpdate {
	if value != nil {
		return nt.SetMaxNotifyTimes(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskUpdateOne) SetNotNilMaxNotifyTimes(value *int8) *NotifyTaskUpdateOne {
	if value != nil {
		return nt.SetMaxNotifyTimes(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskCreate) SetNotNilMaxNotifyTimes(value *int8) *NotifyTaskCreate {
	if value != nil {
		return nt.SetMaxNotifyTimes(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskUpdate) SetNotNilNotifyURL(value *string) *NotifyTaskUpdate {
	if value != nil {
		return nt.SetNotifyURL(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskUpdateOne) SetNotNilNotifyURL(value *string) *NotifyTaskUpdateOne {
	if value != nil {
		return nt.SetNotifyURL(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (nt *NotifyTaskCreate) SetNotNilNotifyURL(value *string) *NotifyTaskCreate {
	if value != nil {
		return nt.SetNotifyURL(*value)
	}
	return nt
}

// set field if value's pointer is not nil.
func (o *OrderUpdate) SetNotNilUpdatedAt(value *time.Time) *OrderUpdate {
	if value != nil {
		return o.SetUpdatedAt(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdateOne) SetNotNilUpdatedAt(value *time.Time) *OrderUpdateOne {
	if value != nil {
		return o.SetUpdatedAt(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderCreate) SetNotNilUpdatedAt(value *time.Time) *OrderCreate {
	if value != nil {
		return o.SetUpdatedAt(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdate) SetNotNilStatus(value *uint8) *OrderUpdate {
	if value != nil {
		return o.SetStatus(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdateOne) SetNotNilStatus(value *uint8) *OrderUpdateOne {
	if value != nil {
		return o.SetStatus(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderCreate) SetNotNilStatus(value *uint8) *OrderCreate {
	if value != nil {
		return o.SetStatus(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdate) SetNotNilDeletedAt(value *time.Time) *OrderUpdate {
	if value != nil {
		return o.SetDeletedAt(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdateOne) SetNotNilDeletedAt(value *time.Time) *OrderUpdateOne {
	if value != nil {
		return o.SetDeletedAt(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderCreate) SetNotNilDeletedAt(value *time.Time) *OrderCreate {
	if value != nil {
		return o.SetDeletedAt(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdate) SetNotNilAppID(value *uint64) *OrderUpdate {
	if value != nil {
		return o.SetAppID(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdateOne) SetNotNilAppID(value *uint64) *OrderUpdateOne {
	if value != nil {
		return o.SetAppID(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderCreate) SetNotNilAppID(value *uint64) *OrderCreate {
	if value != nil {
		return o.SetAppID(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdate) SetNotNilChannelID(value *uint64) *OrderUpdate {
	if value != nil {
		return o.SetChannelID(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdateOne) SetNotNilChannelID(value *uint64) *OrderUpdateOne {
	if value != nil {
		return o.SetChannelID(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderCreate) SetNotNilChannelID(value *uint64) *OrderCreate {
	if value != nil {
		return o.SetChannelID(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdate) SetNotNilChannelCode(value *string) *OrderUpdate {
	if value != nil {
		return o.SetChannelCode(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdateOne) SetNotNilChannelCode(value *string) *OrderUpdateOne {
	if value != nil {
		return o.SetChannelCode(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderCreate) SetNotNilChannelCode(value *string) *OrderCreate {
	if value != nil {
		return o.SetChannelCode(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdate) SetNotNilMerchantOrderID(value *string) *OrderUpdate {
	if value != nil {
		return o.SetMerchantOrderID(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdateOne) SetNotNilMerchantOrderID(value *string) *OrderUpdateOne {
	if value != nil {
		return o.SetMerchantOrderID(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderCreate) SetNotNilMerchantOrderID(value *string) *OrderCreate {
	if value != nil {
		return o.SetMerchantOrderID(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdate) SetNotNilSubject(value *string) *OrderUpdate {
	if value != nil {
		return o.SetSubject(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdateOne) SetNotNilSubject(value *string) *OrderUpdateOne {
	if value != nil {
		return o.SetSubject(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderCreate) SetNotNilSubject(value *string) *OrderCreate {
	if value != nil {
		return o.SetSubject(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdate) SetNotNilBody(value *string) *OrderUpdate {
	if value != nil {
		return o.SetBody(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdateOne) SetNotNilBody(value *string) *OrderUpdateOne {
	if value != nil {
		return o.SetBody(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderCreate) SetNotNilBody(value *string) *OrderCreate {
	if value != nil {
		return o.SetBody(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdate) SetNotNilNotifyURL(value *string) *OrderUpdate {
	if value != nil {
		return o.SetNotifyURL(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdateOne) SetNotNilNotifyURL(value *string) *OrderUpdateOne {
	if value != nil {
		return o.SetNotifyURL(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderCreate) SetNotNilNotifyURL(value *string) *OrderCreate {
	if value != nil {
		return o.SetNotifyURL(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdate) SetNotNilPrice(value *int32) *OrderUpdate {
	if value != nil {
		return o.SetPrice(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdateOne) SetNotNilPrice(value *int32) *OrderUpdateOne {
	if value != nil {
		return o.SetPrice(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderCreate) SetNotNilPrice(value *int32) *OrderCreate {
	if value != nil {
		return o.SetPrice(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdate) SetNotNilChannelFeeRate(value *float64) *OrderUpdate {
	if value != nil {
		return o.SetChannelFeeRate(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdateOne) SetNotNilChannelFeeRate(value *float64) *OrderUpdateOne {
	if value != nil {
		return o.SetChannelFeeRate(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderCreate) SetNotNilChannelFeeRate(value *float64) *OrderCreate {
	if value != nil {
		return o.SetChannelFeeRate(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdate) SetNotNilChannelFeePrice(value *int32) *OrderUpdate {
	if value != nil {
		return o.SetChannelFeePrice(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdateOne) SetNotNilChannelFeePrice(value *int32) *OrderUpdateOne {
	if value != nil {
		return o.SetChannelFeePrice(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderCreate) SetNotNilChannelFeePrice(value *int32) *OrderCreate {
	if value != nil {
		return o.SetChannelFeePrice(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdate) SetNotNilUserIP(value *string) *OrderUpdate {
	if value != nil {
		return o.SetUserIP(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdateOne) SetNotNilUserIP(value *string) *OrderUpdateOne {
	if value != nil {
		return o.SetUserIP(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderCreate) SetNotNilUserIP(value *string) *OrderCreate {
	if value != nil {
		return o.SetUserIP(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdate) SetNotNilExpireTime(value *time.Time) *OrderUpdate {
	if value != nil {
		return o.SetExpireTime(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdateOne) SetNotNilExpireTime(value *time.Time) *OrderUpdateOne {
	if value != nil {
		return o.SetExpireTime(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderCreate) SetNotNilExpireTime(value *time.Time) *OrderCreate {
	if value != nil {
		return o.SetExpireTime(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdate) SetNotNilSuccessTime(value *time.Time) *OrderUpdate {
	if value != nil {
		return o.SetSuccessTime(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdateOne) SetNotNilSuccessTime(value *time.Time) *OrderUpdateOne {
	if value != nil {
		return o.SetSuccessTime(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderCreate) SetNotNilSuccessTime(value *time.Time) *OrderCreate {
	if value != nil {
		return o.SetSuccessTime(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdate) SetNotNilNotifyTime(value *time.Time) *OrderUpdate {
	if value != nil {
		return o.SetNotifyTime(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdateOne) SetNotNilNotifyTime(value *time.Time) *OrderUpdateOne {
	if value != nil {
		return o.SetNotifyTime(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderCreate) SetNotNilNotifyTime(value *time.Time) *OrderCreate {
	if value != nil {
		return o.SetNotifyTime(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdate) SetNotNilExtensionID(value *uint64) *OrderUpdate {
	if value != nil {
		return o.SetExtensionID(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdateOne) SetNotNilExtensionID(value *uint64) *OrderUpdateOne {
	if value != nil {
		return o.SetExtensionID(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderCreate) SetNotNilExtensionID(value *uint64) *OrderCreate {
	if value != nil {
		return o.SetExtensionID(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdate) SetNotNilNo(value *string) *OrderUpdate {
	if value != nil {
		return o.SetNo(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdateOne) SetNotNilNo(value *string) *OrderUpdateOne {
	if value != nil {
		return o.SetNo(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderCreate) SetNotNilNo(value *string) *OrderCreate {
	if value != nil {
		return o.SetNo(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdate) SetNotNilRefundPrice(value *int32) *OrderUpdate {
	if value != nil {
		return o.SetRefundPrice(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdateOne) SetNotNilRefundPrice(value *int32) *OrderUpdateOne {
	if value != nil {
		return o.SetRefundPrice(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderCreate) SetNotNilRefundPrice(value *int32) *OrderCreate {
	if value != nil {
		return o.SetRefundPrice(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdate) SetNotNilChannelUserID(value *string) *OrderUpdate {
	if value != nil {
		return o.SetChannelUserID(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdateOne) SetNotNilChannelUserID(value *string) *OrderUpdateOne {
	if value != nil {
		return o.SetChannelUserID(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderCreate) SetNotNilChannelUserID(value *string) *OrderCreate {
	if value != nil {
		return o.SetChannelUserID(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdate) SetNotNilChannelOrderNo(value *string) *OrderUpdate {
	if value != nil {
		return o.SetChannelOrderNo(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderUpdateOne) SetNotNilChannelOrderNo(value *string) *OrderUpdateOne {
	if value != nil {
		return o.SetChannelOrderNo(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (o *OrderCreate) SetNotNilChannelOrderNo(value *string) *OrderCreate {
	if value != nil {
		return o.SetChannelOrderNo(*value)
	}
	return o
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionUpdate) SetNotNilUpdatedAt(value *time.Time) *OrderExtensionUpdate {
	if value != nil {
		return oe.SetUpdatedAt(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionUpdateOne) SetNotNilUpdatedAt(value *time.Time) *OrderExtensionUpdateOne {
	if value != nil {
		return oe.SetUpdatedAt(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionCreate) SetNotNilUpdatedAt(value *time.Time) *OrderExtensionCreate {
	if value != nil {
		return oe.SetUpdatedAt(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionUpdate) SetNotNilStatus(value *uint8) *OrderExtensionUpdate {
	if value != nil {
		return oe.SetStatus(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionUpdateOne) SetNotNilStatus(value *uint8) *OrderExtensionUpdateOne {
	if value != nil {
		return oe.SetStatus(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionCreate) SetNotNilStatus(value *uint8) *OrderExtensionCreate {
	if value != nil {
		return oe.SetStatus(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionUpdate) SetNotNilDeletedAt(value *time.Time) *OrderExtensionUpdate {
	if value != nil {
		return oe.SetDeletedAt(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionUpdateOne) SetNotNilDeletedAt(value *time.Time) *OrderExtensionUpdateOne {
	if value != nil {
		return oe.SetDeletedAt(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionCreate) SetNotNilDeletedAt(value *time.Time) *OrderExtensionCreate {
	if value != nil {
		return oe.SetDeletedAt(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionUpdate) SetNotNilNo(value *string) *OrderExtensionUpdate {
	if value != nil {
		return oe.SetNo(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionUpdateOne) SetNotNilNo(value *string) *OrderExtensionUpdateOne {
	if value != nil {
		return oe.SetNo(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionCreate) SetNotNilNo(value *string) *OrderExtensionCreate {
	if value != nil {
		return oe.SetNo(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionUpdate) SetNotNilOrderID(value *uint64) *OrderExtensionUpdate {
	if value != nil {
		return oe.SetOrderID(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionUpdateOne) SetNotNilOrderID(value *uint64) *OrderExtensionUpdateOne {
	if value != nil {
		return oe.SetOrderID(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionCreate) SetNotNilOrderID(value *uint64) *OrderExtensionCreate {
	if value != nil {
		return oe.SetOrderID(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionUpdate) SetNotNilChannelID(value *uint64) *OrderExtensionUpdate {
	if value != nil {
		return oe.SetChannelID(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionUpdateOne) SetNotNilChannelID(value *uint64) *OrderExtensionUpdateOne {
	if value != nil {
		return oe.SetChannelID(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionCreate) SetNotNilChannelID(value *uint64) *OrderExtensionCreate {
	if value != nil {
		return oe.SetChannelID(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionUpdate) SetNotNilChannelCode(value *string) *OrderExtensionUpdate {
	if value != nil {
		return oe.SetChannelCode(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionUpdateOne) SetNotNilChannelCode(value *string) *OrderExtensionUpdateOne {
	if value != nil {
		return oe.SetChannelCode(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionCreate) SetNotNilChannelCode(value *string) *OrderExtensionCreate {
	if value != nil {
		return oe.SetChannelCode(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionUpdate) SetNotNilUserIP(value *string) *OrderExtensionUpdate {
	if value != nil {
		return oe.SetUserIP(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionUpdateOne) SetNotNilUserIP(value *string) *OrderExtensionUpdateOne {
	if value != nil {
		return oe.SetUserIP(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionCreate) SetNotNilUserIP(value *string) *OrderExtensionCreate {
	if value != nil {
		return oe.SetUserIP(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionUpdate) SetNotNilChannelExtras(value *map[string]string) *OrderExtensionUpdate {
	if value != nil {
		return oe.SetChannelExtras(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionUpdateOne) SetNotNilChannelExtras(value *map[string]string) *OrderExtensionUpdateOne {
	if value != nil {
		return oe.SetChannelExtras(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionCreate) SetNotNilChannelExtras(value *map[string]string) *OrderExtensionCreate {
	if value != nil {
		return oe.SetChannelExtras(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionUpdate) SetNotNilChannelErrorCode(value *string) *OrderExtensionUpdate {
	if value != nil {
		return oe.SetChannelErrorCode(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionUpdateOne) SetNotNilChannelErrorCode(value *string) *OrderExtensionUpdateOne {
	if value != nil {
		return oe.SetChannelErrorCode(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionCreate) SetNotNilChannelErrorCode(value *string) *OrderExtensionCreate {
	if value != nil {
		return oe.SetChannelErrorCode(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionUpdate) SetNotNilChannelErrorMsg(value *string) *OrderExtensionUpdate {
	if value != nil {
		return oe.SetChannelErrorMsg(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionUpdateOne) SetNotNilChannelErrorMsg(value *string) *OrderExtensionUpdateOne {
	if value != nil {
		return oe.SetChannelErrorMsg(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionCreate) SetNotNilChannelErrorMsg(value *string) *OrderExtensionCreate {
	if value != nil {
		return oe.SetChannelErrorMsg(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionUpdate) SetNotNilChannelNotifyData(value *string) *OrderExtensionUpdate {
	if value != nil {
		return oe.SetChannelNotifyData(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionUpdateOne) SetNotNilChannelNotifyData(value *string) *OrderExtensionUpdateOne {
	if value != nil {
		return oe.SetChannelNotifyData(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (oe *OrderExtensionCreate) SetNotNilChannelNotifyData(value *string) *OrderExtensionCreate {
	if value != nil {
		return oe.SetChannelNotifyData(*value)
	}
	return oe
}

// set field if value's pointer is not nil.
func (r *RefundUpdate) SetNotNilUpdatedAt(value *time.Time) *RefundUpdate {
	if value != nil {
		return r.SetUpdatedAt(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdateOne) SetNotNilUpdatedAt(value *time.Time) *RefundUpdateOne {
	if value != nil {
		return r.SetUpdatedAt(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundCreate) SetNotNilUpdatedAt(value *time.Time) *RefundCreate {
	if value != nil {
		return r.SetUpdatedAt(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdate) SetNotNilStatus(value *uint8) *RefundUpdate {
	if value != nil {
		return r.SetStatus(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdateOne) SetNotNilStatus(value *uint8) *RefundUpdateOne {
	if value != nil {
		return r.SetStatus(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundCreate) SetNotNilStatus(value *uint8) *RefundCreate {
	if value != nil {
		return r.SetStatus(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdate) SetNotNilDeletedAt(value *time.Time) *RefundUpdate {
	if value != nil {
		return r.SetDeletedAt(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdateOne) SetNotNilDeletedAt(value *time.Time) *RefundUpdateOne {
	if value != nil {
		return r.SetDeletedAt(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundCreate) SetNotNilDeletedAt(value *time.Time) *RefundCreate {
	if value != nil {
		return r.SetDeletedAt(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdate) SetNotNilNo(value *string) *RefundUpdate {
	if value != nil {
		return r.SetNo(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdateOne) SetNotNilNo(value *string) *RefundUpdateOne {
	if value != nil {
		return r.SetNo(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundCreate) SetNotNilNo(value *string) *RefundCreate {
	if value != nil {
		return r.SetNo(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdate) SetNotNilAppID(value *uint64) *RefundUpdate {
	if value != nil {
		return r.SetAppID(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdateOne) SetNotNilAppID(value *uint64) *RefundUpdateOne {
	if value != nil {
		return r.SetAppID(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundCreate) SetNotNilAppID(value *uint64) *RefundCreate {
	if value != nil {
		return r.SetAppID(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdate) SetNotNilChannelID(value *uint64) *RefundUpdate {
	if value != nil {
		return r.SetChannelID(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdateOne) SetNotNilChannelID(value *uint64) *RefundUpdateOne {
	if value != nil {
		return r.SetChannelID(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundCreate) SetNotNilChannelID(value *uint64) *RefundCreate {
	if value != nil {
		return r.SetChannelID(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdate) SetNotNilChannelCode(value *string) *RefundUpdate {
	if value != nil {
		return r.SetChannelCode(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdateOne) SetNotNilChannelCode(value *string) *RefundUpdateOne {
	if value != nil {
		return r.SetChannelCode(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundCreate) SetNotNilChannelCode(value *string) *RefundCreate {
	if value != nil {
		return r.SetChannelCode(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdate) SetNotNilOrderID(value *uint64) *RefundUpdate {
	if value != nil {
		return r.SetOrderID(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdateOne) SetNotNilOrderID(value *uint64) *RefundUpdateOne {
	if value != nil {
		return r.SetOrderID(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundCreate) SetNotNilOrderID(value *uint64) *RefundCreate {
	if value != nil {
		return r.SetOrderID(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdate) SetNotNilOrderNo(value *string) *RefundUpdate {
	if value != nil {
		return r.SetOrderNo(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdateOne) SetNotNilOrderNo(value *string) *RefundUpdateOne {
	if value != nil {
		return r.SetOrderNo(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundCreate) SetNotNilOrderNo(value *string) *RefundCreate {
	if value != nil {
		return r.SetOrderNo(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdate) SetNotNilMerchantOrderID(value *string) *RefundUpdate {
	if value != nil {
		return r.SetMerchantOrderID(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdateOne) SetNotNilMerchantOrderID(value *string) *RefundUpdateOne {
	if value != nil {
		return r.SetMerchantOrderID(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundCreate) SetNotNilMerchantOrderID(value *string) *RefundCreate {
	if value != nil {
		return r.SetMerchantOrderID(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdate) SetNotNilMerchantRefundID(value *string) *RefundUpdate {
	if value != nil {
		return r.SetMerchantRefundID(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdateOne) SetNotNilMerchantRefundID(value *string) *RefundUpdateOne {
	if value != nil {
		return r.SetMerchantRefundID(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundCreate) SetNotNilMerchantRefundID(value *string) *RefundCreate {
	if value != nil {
		return r.SetMerchantRefundID(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdate) SetNotNilNotifyURL(value *string) *RefundUpdate {
	if value != nil {
		return r.SetNotifyURL(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdateOne) SetNotNilNotifyURL(value *string) *RefundUpdateOne {
	if value != nil {
		return r.SetNotifyURL(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundCreate) SetNotNilNotifyURL(value *string) *RefundCreate {
	if value != nil {
		return r.SetNotifyURL(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdate) SetNotNilPayPrice(value *int32) *RefundUpdate {
	if value != nil {
		return r.SetPayPrice(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdateOne) SetNotNilPayPrice(value *int32) *RefundUpdateOne {
	if value != nil {
		return r.SetPayPrice(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundCreate) SetNotNilPayPrice(value *int32) *RefundCreate {
	if value != nil {
		return r.SetPayPrice(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdate) SetNotNilRefundPrice(value *int32) *RefundUpdate {
	if value != nil {
		return r.SetRefundPrice(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdateOne) SetNotNilRefundPrice(value *int32) *RefundUpdateOne {
	if value != nil {
		return r.SetRefundPrice(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundCreate) SetNotNilRefundPrice(value *int32) *RefundCreate {
	if value != nil {
		return r.SetRefundPrice(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdate) SetNotNilReason(value *string) *RefundUpdate {
	if value != nil {
		return r.SetReason(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdateOne) SetNotNilReason(value *string) *RefundUpdateOne {
	if value != nil {
		return r.SetReason(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundCreate) SetNotNilReason(value *string) *RefundCreate {
	if value != nil {
		return r.SetReason(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdate) SetNotNilUserIP(value *string) *RefundUpdate {
	if value != nil {
		return r.SetUserIP(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdateOne) SetNotNilUserIP(value *string) *RefundUpdateOne {
	if value != nil {
		return r.SetUserIP(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundCreate) SetNotNilUserIP(value *string) *RefundCreate {
	if value != nil {
		return r.SetUserIP(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdate) SetNotNilChannelOrderNo(value *string) *RefundUpdate {
	if value != nil {
		return r.SetChannelOrderNo(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdateOne) SetNotNilChannelOrderNo(value *string) *RefundUpdateOne {
	if value != nil {
		return r.SetChannelOrderNo(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundCreate) SetNotNilChannelOrderNo(value *string) *RefundCreate {
	if value != nil {
		return r.SetChannelOrderNo(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdate) SetNotNilChannelRefundNo(value *string) *RefundUpdate {
	if value != nil {
		return r.SetChannelRefundNo(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdateOne) SetNotNilChannelRefundNo(value *string) *RefundUpdateOne {
	if value != nil {
		return r.SetChannelRefundNo(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundCreate) SetNotNilChannelRefundNo(value *string) *RefundCreate {
	if value != nil {
		return r.SetChannelRefundNo(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdate) SetNotNilSuccessTime(value *time.Time) *RefundUpdate {
	if value != nil {
		return r.SetSuccessTime(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdateOne) SetNotNilSuccessTime(value *time.Time) *RefundUpdateOne {
	if value != nil {
		return r.SetSuccessTime(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundCreate) SetNotNilSuccessTime(value *time.Time) *RefundCreate {
	if value != nil {
		return r.SetSuccessTime(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdate) SetNotNilChannelErrorCode(value *string) *RefundUpdate {
	if value != nil {
		return r.SetChannelErrorCode(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdateOne) SetNotNilChannelErrorCode(value *string) *RefundUpdateOne {
	if value != nil {
		return r.SetChannelErrorCode(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundCreate) SetNotNilChannelErrorCode(value *string) *RefundCreate {
	if value != nil {
		return r.SetChannelErrorCode(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdate) SetNotNilChannelErrorMsg(value *string) *RefundUpdate {
	if value != nil {
		return r.SetChannelErrorMsg(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdateOne) SetNotNilChannelErrorMsg(value *string) *RefundUpdateOne {
	if value != nil {
		return r.SetChannelErrorMsg(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundCreate) SetNotNilChannelErrorMsg(value *string) *RefundCreate {
	if value != nil {
		return r.SetChannelErrorMsg(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdate) SetNotNilChannelNotifyData(value *string) *RefundUpdate {
	if value != nil {
		return r.SetChannelNotifyData(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundUpdateOne) SetNotNilChannelNotifyData(value *string) *RefundUpdateOne {
	if value != nil {
		return r.SetChannelNotifyData(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *RefundCreate) SetNotNilChannelNotifyData(value *string) *RefundCreate {
	if value != nil {
		return r.SetChannelNotifyData(*value)
	}
	return r
}
